name-tag:
  - "v*"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
categories:
  - title: "Breaking Changes"
    labels:
      - "breaking"
      - "major"
  - title: "Yenilikler"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "Hata Düzeltmeleri"
    labels:
      - "fix"
      - "bug"
  - title: "Dokümantasyon"
    labels:
      - "docs"
  - title: "Refactor & Test"
    labels:
      - "refactor"
      - "test"
      - "chore"
exclude-labels:
  - "skip-changelog"
template: |
  ## Yenilikler

  $CHANGES
version-resolver:
  major:
    labels:
      - "breaking"
      - "major"
  minor:
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bug"
      - "docs"
      - "chore"
      - "refactor"
      - "test"
